### ISSUE TITLE
Can't get PrintfulClient to load from namespace?

### ISSUE THREAD

**Issue by georgemandis** [printful/php-api-sdk#1]
I'm working on an app that uses the [Slim framework](https://www.slimframework.com/) and composer to manage its dependencies. I'm running into problems with the Printful PHP API SDK. All of my other dependencies so far have worked just fine:

"slim/slim": "^3.0",
"slim/twig-view": "^2.2",
"dflydev/fig-cookies": "^1.0",
"aws/aws-sdk-php": "^3.22",
"printful/php-api-sdk": "^1.0"

I'm using the code in `examples/orders.php` and it's telling me: Fatal error: `Class 'Printful\PrintfulApi\PrintfulClient' not found`

I've double checked and `printful/php-api-sdk`  definitely exists in my `vendors` folder and appears to be installed correctly. I move the orders.php file to a place where it was correctly loading my `vendor/autoload.php` file as well and confirmed I could access other classes from my dependencies using their namespace (Aws\S3\S3Client for example).

I tried deleting everything in `vendor` and reinstalling with composer. Everything reinstalled and worked correctly except for this package.

Any thoughts on what the issue might be? I recognize this might not necessarily be a Printful PHP SDK issue, but I'm a little stumped.

Thanks!

**Comment by briedis** [comment]
Hey there!

I've just realesed a newer version, **v2.0**, but it is not compatible with previous versions, because Api class name has changedand versions too, but it should not take much time to fix the code if you have already implemented something with this library.

Give it a go, and let us know if we can help!

**Comment by georgemandis** [comment]
That fixed the problem! Thank you :)
