### ISSUE TITLE
Printful Mockup Generation task - All-Over-Shirt (Product id 257)

### ISSUE THREAD

**Issue by 386er** [printful/php-api-sdk#22]
Hi,

I am currently in the process of setting up an online store where users can select a design and a request will be sent to printful via API.

A part of this will be to create a mockup design first that is presented to the customer. We are already able to create a mockup for a standard shirt (API Product Id 71)

However, we are currently not able to create a mockup for All-Over shirts (API-Product ID 257)

When we create a mockup generation task (see request body below), we get the following error message:

{
    "code": 400,
    "result": "No variants to generate. Option filters may exclude all variants or variants are not available.",
    "error": {
        "reason": "BadRequest",
        "message": "No variants to generate. Option filters may exclude all variants or variants are not available."
    }
}

The API documentation is not really clear on how the request body should look like for All-Over-Shirts. Especialls the role of "options". 
####

{
"variant_ids": [8855],
"format": "png",
"option_groups": ["Wrinkled"],
 "options": ["Front"],
"files": [
{
"placement": "default",
"image_url": "https://s3-eu-central-1.amazonaws.com/image-bucket-scrawl/palmtree/1598566557/pattern.png",
"position": {
"area_width": 4200,
"area_height": 5400,
"width": 5400,
"height": 5400,
"top": 0,
"left": 0
}
},
{
"placement": "back",
"image_url": "https://s3-eu-central-1.amazonaws.com/image-bucket-scrawl/palmtree/1598566557/pattern.png",
"position": {
"area_width": 4200,
"area_height": 5400,
"width": 5400,
"height": 5400,
"top": 0,
"left": 0
}
},
{
"placement": "sleeve_left",
"image_url": "https://s3-eu-central-1.amazonaws.com/image-bucket-scrawl/palmtree/1598566557/pattern.png",
"position": {
"area_width": 3000,
"area_height": 1800,
"width": 3000,
"height": 3000,
"top": 0,
"left": 0
}
},
{
"placement": "sleeve_right",
"image_url": "https://s3-eu-central-1.amazonaws.com/image-bucket-scrawl/palmtree/1598566557/pattern.png",
"position": {
"area_width": 3000,
"area_height": 1800,
"width": 3000,
"height": 3000,
"top": 0,
"left": 0
}
}

]
}

**Comment by rkistaps** [comment]
Hello. Sorry for the late response. This library is just an SDK for working with the API. If there are questions about the API, you should contact our API support team - devsupport@printful.com.
