### ISSUE TITLE
Allow for creating items using new keyword

### ISSUE THREAD

**Issue by scorgn** [printful/php-api-sdk#25]
Hey guys.

I am implementing the API here and I'm noticing that all your objects are creating using the `public static function fromArray(array $rawData)` method. It sure does make things simple, I personally prefer the static factory method myself when working on personal projects.

But I'm a little bit confused on why that's the only way to create an item from an array of data. It seems as if it would be just as simple to define a `public function __construct(array $rawData)` method as well, which the `fromArray(array $rawData)` method could utilize. This would allow people to also be able to create the object by using `new Item(...)`.

So this would look like...

```php
abstract class BaseItem
{
    public function __construct(array $rawData)
    {
       $this->setData($rawData);
    }

    public static function fromArray(array $raw)
    {
        return new static($raw);
    }

    public function setData(array $raw)
    {
        throw new PrintfulException(
            __CLASS__ . ' does not have setData() implementation. ' .
            'Data given: ' . print_r($raw, true)
        );
    }
}
```

And then in each class extending BaseItem you would just need to change the `public static function fromArray(array $raw)` to `public function setData(array $raw)`.

Is this something you guys would be interested in doing? If so, I would be happy to make the code changes and create a pull request. It would be a non-breaking change since it would only add additional functionality, so it would only be a minor version change.

**Comment by rkistaps** [comment]
Hello. Thanks for your comment, but it seems like just another way of doing things without giving any additional benefit.
