### ISSUE TITLE
Composer Issue

### ISSUE THREAD

**Issue by kas5986** [printful/php-api-sdk#8]
Problem 1
    - The requested package printful/php-api-sdk No version set (parsed as 1.0.0) is satisfiable by printful/php-api-sdk[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

**Comment by briedis** [comment]
How exactly are you trying to install the package?
Can you show me your composer.json file?

No problems occured when I tried adding it to a new project:
![image](https://user-images.githubusercontent.com/500491/34104292-8068ca72-e3f8-11e7-8abd-3e487a0ca7cd.png)

**Comment by briedis** [comment]
@kas5986 how about that composer.json file? :)

**Comment by kas5986** [comment]
the file i did download the package but using your composer.json it is giving the same error

**Comment by briedis** [comment]
Hmm. Do you have any prior experience with composer?
If not, please refer to docs: https://getcomposer.org/doc/01-basic-usage.md

It should work like this (if your project already uses composer, skip 1. and 2. step.

1. Verify that composer is installed
2. Open up your project and write `composer init`, follow the steps
3. When composer.json file appears in your project root, call `composer require printful/php-api-sdk` and package should get installed.

**Comment by kas5986** [comment]
i have used composer before not much experience with that but i use composer.json file and just run the command and it works but in your case by downloading composer.json from your repo it is not making it to download all the stuff

**Comment by kas5986** [comment]
this is my JSON file looks like and it downloaded everything

{
    "name": "shafi/dokan-printful-integration",
    "require": {
        "printful/php-api-sdk": "^2.1"
    }
}

**Comment by kas5986** [comment]
and in auto-loadisntn't loading the class when i try instansiateate it to get data from your server

**Comment by briedis** [comment]
Maybe this tutorial will help? 
https://www.codementor.io/jadjoubran/php-tutorial-getting-started-with-composer-8sbn6fb6t

This shows how to use a composer package in a plain PHP project (without frameworks).
